MSG * Para continuar, clique em OK
MSG * Extraindo dados...
MSG * Extraindo dados...
MSG * Extraindo dados...
MSG * Fazendo dowloand...
MSG * Fazendo dowloand...
MSG * Fazendo dowloand...
MSG * Fazendo dowloand...
MSG * Foi impossivel instalar, parece que Aurora Injector não funciona em seu dispositivo!